#!/bin/sh
# Creates an "Install GXDE" icon on the live session tested with:
# Xfce, LXDE, LXqt, Gnome, KDE, Mate, Cinnamon

# We query xdg-user-dir because the Desktop directory has different
# names for different languages
DESKTOP=$(xdg-user-dir DESKTOP)

# Create ~/Desktop just in case this runs before the xdg folder
# creation script.
mkdir -p $DESKTOP

# Among the GXDE desktop environments, LXDE is the only one
# that behaves completely different.
if [ -f /usr/bin/lxsession ]; then
    echo "[Desktop Entry]" > $DESKTOP/install-gxde.desktop
    echo "Type=Link" >> $DESKTOP/install-gxde.desktop
    echo "Name=Install GXDE" >> $DESKTOP/install-gxde.desktop
    echo "Icon=install-gxde" >> $DESKTOP/install-gxde.desktop
    echo "URL=/usr/share/applications/install-gxde.desktop" \
          >> $DESKTOP/install-gxde.desktop
else
    cp /usr/share/applications/install-gxde.desktop $DESKTOP
    # Xfce needs this executable otherwise it complains, everything
    # else doesn't seem to care either way.
    chmod +x $DESKTOP/install-gxde.desktop
fi
